#!/usr/bin/env python3
"""Build all four poster variants and their PNG previews.

Variant 1 — Polished Classic — is the canonical poster produced by
``scripts/build_poster.py``; we re-run that script and copy the result
into ``poster/variants/`` so all four variants live side-by-side.

Variants 2/3/4 are generated by their respective ``build_*`` modules in
this package.  All variant .pptx files are byte-identical across runs
thanks to deterministic ZIP normalisation, so the artifacts are
diffable in code review.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys

from scripts.variants._common import (
    POSTER_DIR, REPO_ROOT, VARIANTS_DIR, render_preview_png,
)
from scripts.variants.build_academic import build as build_academic
from scripts.variants.build_editorial import build as build_editorial
from scripts.variants.build_minimal import build as build_minimal


def _ensure_polished_classic():
    """Re-run the Polished Classic builder, then copy its outputs."""
    canonical_pptx = os.path.join(POSTER_DIR, "poster.pptx")
    canonical_png = os.path.join(POSTER_DIR, "poster_preview.png")
    build_script = os.path.join(REPO_ROOT, "scripts", "build_poster.py")
    subprocess.run([sys.executable, build_script], check=True, cwd=REPO_ROOT,
                   capture_output=True)
    os.makedirs(VARIANTS_DIR, exist_ok=True)
    dest_pptx = os.path.join(VARIANTS_DIR, "variant_1_polished_classic.pptx")
    dest_png = os.path.join(VARIANTS_DIR, "variant_1_polished_classic_preview.png")
    shutil.copyfile(canonical_pptx, dest_pptx)
    if os.path.exists(canonical_png):
        shutil.copyfile(canonical_png, dest_png)
    else:
        # If the canonical PNG didn't render (LibreOffice missing in CI), try
        # producing one from the .pptx we just copied.
        render_preview_png(dest_pptx, dest_png)
    return dest_pptx, dest_png


def build_all():
    outputs = []
    outputs.append(_ensure_polished_classic())
    outputs.append(build_editorial())
    outputs.append(build_academic())
    outputs.append(build_minimal())
    return outputs


if __name__ == "__main__":
    for pptx, png in build_all():
        print(f"wrote {pptx}")
        print(f"wrote {png}")
